#!/bin/bash

dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
fil=${dir}/tulip.xcodeproj/project.pbxproj

if [[ -f ${fil} ]] ; then

    echo "v$(grep MARKETING_VERSION ${fil} | awk '{print $3}' | sed 's/;//g' | head -n 1)"

else

    >&2 echo "Cannot find version file!"
    exit 1

fi

exit 0
